services:
  db:
    image: mysql:latest
    command: ["--mysql-native-password=ON"]
    environment:
      MYSQL_ROOT_PASSWORD: Secret5555
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8080:8080

volumes:
  mysql_db_data_container: